# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.32.1"

before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
end

after_all do |lane|
  notification(
    title: "Fastlane '#{lane}'",
    message: "finished successfully"
  )
end

error do |lane, exception|
  notification(
    title: "Fastlane '#{lane}'",
    message: "Failed: #{exception.message}"
  )
  UI.error "exception: #{exception.message}"
end

desc "Will Check and show all fastlane dependencies, also downloads/updates them for you"
lane :dependencies do
  lg_dependencies(
    lg_just_info: false
  )
end

desc "Will update project strings reading from the provided Google spreadsheet"
lane :strings do
  lg_strings(
    repository_path: "./",
    mark_unused_strings: false
  )
end
